### ISSUE TITLE
Petite Erreur (surement dû à un copier coller) 

### ISSUE THREAD

**Issue by RiviereV** [fpluquet/csharp-intro#1]
![image](https://user-images.githubusercontent.com/91625539/135314548-2ad3e260-4739-4353-b60b-bbd9d4d36f6d.png)
le morceau de code suivant devrait être modifié par EndsWith (je le notifie juste au cas où).

**Comment by fpluquet** [comment]
Merci de l'avoir signalé. C'est corrigé.
